Implement centroids ellipses
NikolajKrogh/P6 pull request #84
Opened 2023-04-24 11:50 UTC by KasperBahrentzAAU

2023-04-24 16:06 UTC, Lildhansen requested changes
har sat et par kommentarer.

Derudover synes jeg også generelt vi lige skal blive enige om det her er noget vi vil. Fordi hvis vores accuracy allerede er jævnt høj, skal vi overveje performance af det her, fordi det er jo noget vi vejer rigtigt højt - måske bare hvor meget vi får ud af det vs hvad det koster i memory / runtime

2023-04-24 16:06 UTC, Lildhansen commented on DataCollection/app/src/main/java/com/example/p6/classes/PreProcessing.java
> +    public static void makeBudgetTimeSeries(List<DataPointRaw> dataPointsToAdd) {
skal vi få ændret dem til aggregatedTimeSeries - eller måske aggregatedTimeWindows hvis det er det det er

2023-04-24 16:06 UTC, Lildhansen commented on DataCollection/app/src/main/java/com/example/p6/classes/PreProcessing.java
> +    private static void checkIfDataPointIsNewEdgeCase(DataPointRaw dataPoint){
synes "check" er lidt et misvisende ord. Check lyder mere som en boolean. Her der både tjekker vi og opdaterer.

Synes bare den burde hedde updateEdgeCases (fordi den opdaterer sjovt nok kun hvis det er nødvendigt)

2023-04-26 10:41 UTC, NikolajKrogh approved these changes

2023-04-26 10:42 UTC, Lildhansen approved these changes

2023-04-26 10:43 UTC, merged